### ISSUE TITLE
Support specifying a base URL via environment variable

### ISSUE THREAD

**Issue by davehunt** [pytest-dev/pytest-base-url#1]
It's already possible to do this using `PYTEST_ADDOPTS` but I think it would be a nice idea to add support for a `PYTEST_BASE_URL` environment variable. If present this would be used, but would be overridden by any other method for specifying the URL.

**Comment by RonnyPfannschmidt** [comment]
perhaps in pytest itself we should think of a way to add/create options that map to ini options, cli options and env vars ?

**Comment by davehunt** [comment]
This was resolved in 981d0f11ab13457940ed87e3abfea1e129765460 and been available since v1.2.0.
