### ISSUE TITLE
Malformed URL: / is not a valid URL

### ISSUE THREAD

**Issue by RuslanBM** [pytest-dev/pytest-base-url#10]
Hello. I got an error, when use base-url for open main page with xdist plugin. My test starts with:
`main_page.open()`

I run it:
`pytest -n 2`

And gets an Error:
`selenium.common.exceptions.InvalidArgumentException: Message: Malformed URL: / is not a valid URL.`

If I not use base_url and go to page this way:
`main_page.open_url('www.google.com')`
and comment it at pytest.ini - everything is good.

My conftest.py have:
@pytest.fixture()
def page_main(selenium):
    return pages.MainPage(selenium)

My Pipfile:
```PyPOM==2.2.0
pytest==5.1.2
pytest-bdd==3.2.1
pytest-xdist==1.31.0
pytest-base-url==1.4.1
pytest-selenium==1.17.0

gcloud==0.18.3
firebase==3.0.1
python_jwt==3.2.4
sseclient-py==1.7
py-postgresql==1.2.1
requests-toolbelt==0.9.1
arrow==0.15.4
kombu==4.6.7
```

My pytest.ini
```
[pytest]
bdd_features_base_dir = tests
base_url = https://projectname.com
sensitive_url = https://projectname.com
addopts = --driver Remote
          --port 4444
          --capability browserName firefox
          --html tests/logs/report.html
          --cucumberjson=tests/uploads/cucumber.json
          --cucumberjson-expanded
          -v
filterwarnings =
    ignore::DeprecationWarning
markers =
    smoke: fast result
    crypto: add calculations
```
Here is track trace:

result = call_fixture_func(fixturefunc, request, kwargs)
../../.pyenv/versions/3.6.8/envs/projectname/lib/python3.6/site-packages/_pytest/fixtures.py:778: in call_fixture_func
    res = fixturefunc(**kwargs)
tests/functional/test_02_deposit_by_dash.py:20: in user_signed_in
    page_main.open()
../../.pyenv/versions/3.6.8/envs/projectname/lib/python3.6/site-packages/pypom/page.py:130: in open
    self.driver_adapter.open(self.seed_url)
../../.pyenv/versions/3.6.8/envs/projectname/lib/python3.6/site-packages/pypom/selenium_driver.py:48: in open
    self.driver.get(url)
../../.pyenv/versions/3.6.8/envs/projectname/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py:333: in get
    self.execute(Command.GET, {'url': url})
../../.pyenv/versions/3.6.8/envs/projectname/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py:321: in execute
    self.error_handler.check_response(response)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x10faa6f98>
response = {'status': 400, 'value': '{"value":{"error":"invalid argument","message":"Malformed URL: / is not a valid URL.","stack...dArgumentError@chrome://marionette/content/error.js:304:5\\nget@chrome://marionette/content/listener.js:1132:19\\n"}}'}
**E       selenium.common.exceptions.InvalidArgumentException: Message: Malformed URL: / is not a valid URL.**

Please help me to figure out usage of base-url plugin or fix It if you can.

**Comment by RuslanBM** [comment]
<img width="1377" alt="Screenshot 2020-03-16 at 13 35 46" src="https://user-images.githubusercontent.com/54805270/76754334-029e3e80-6793-11ea-9299-358f3a65917b.png">

**Comment by BeyondEvil** [comment]
Can you create a small reproducible case? In your repro steps there's still a lot of your own code (pages etc.).

You can fork the pytest-playground repo to set it up. Let me know if you need any help. I'll try to update the README with some info.

**Comment by Ruslang** [comment]
Please try it, and you are Welcome to improve everything that you consider necessary here:
https://github.com/Ruslang/pytest-selenium-bdd

**Comment by Ruslang** [comment]
I use this structure on my project and i need to run it at parallel...

**Comment by BeyondEvil** [comment]
Here's the problem: https://github.com/Ruslang/pytest-selenium-bdd/blob/master/tests/functional/pages/main.py#L9

Which the error message actually eludes to: `Message: Malformed URL: / is not a valid URL.`

**/** is not a valid URL.

The `base_url` in your `pytest.ini` is for this plugin, not for PyPOM. If you want PyPOM to use the base URL (seed URL) you need to set it.

Change [this](https://github.com/Ruslang/pytest-selenium-bdd/blob/master/tests/functional/conftest.py#L35-L37) to:
```python
@pytest.fixture()
def page_main(base_url, selenium):
    return pages.MainPage(selenium, base_url=base_url)
```

Good luck! @RuslanBM

**Comment by RuslanBM** [comment]
Thanks! This is works. How I can get `base_url` value from pytest.ini available for use at my PyPOM Class?

**Comment by BeyondEvil** [comment]
Great to hear it!

You'll have to add an `__init__` to `MainPage` and save the `base_url` there before passing it to the parent (`BasePage` by calling `super()`).

Good luck!
