### ISSUE TITLE
[Feature] Support Pytest v8

### ISSUE THREAD

**Issue by mxschmitt** [pytest-dev/pytest-base-url#41]
This requires releasing a new version, since the require was already relaxed in https://github.com/pytest-dev/pytest-base-url/commit/21ed6acc39fcb350676414ff1cb6ee3106223e64.

**Comment by sallner** [comment]
Yes, I would also encourage a release @davehunt Would you still be available for that?

**Comment by BeyondEvil** [comment]
[2.1.0](https://pypi.org/project/pytest-base-url/) is now live!
