### ISSUE TITLE
`pytest.config` removed

### ISSUE THREAD

**Issue by OJFord** [pytest-dev/pytest-base-url#8]
The readme suggests:
```python
@pytest.mark.skipif(
    'dev' in pytest.config.getoption('base_url'),
    reason='Search not available on dev')
```

but use of `pytest.config` is deprecated in v4 and removed in v5. (Latest stable release as of writing is 5.1.2.)

Not clear to me what the best recommendation is now, there's a `pytestconfig` fixture, but since it's a fixture it can't be used in a mark.

Skipping in the body of the test is inelegant for a common case, but perhaps it's the only solution.

**Comment by BeyondEvil** [comment]
You can deal with it by using `string conditions`:
```
@pytest.mark.skipif(
    "'dev' in config.getoption('base_url')",
    reason='Search not available on dev')
```
https://docs.pytest.org/en/latest/historical-notes.html#string-conditions

Looking at the docs however that seems to be the "old" way of doing it, and the "new" way being the now deprecated way. 🤷‍♂

**Comment by BeyondEvil** [comment]
Ok, reading through old issues I think the recommended way now, is to create your own marker and then use the `-m` flag when running `pytest`.

**Comment by BeyondEvil** [comment]
ping @nicoddemus

**Comment by nicoddemus** [comment]
Sorry for the delay!

You can use strings instead to obtain the same effect:

```python
@pytest.mark.skipif(
    "'dev' in config.getoption('base_url')",
    reason='Search not available on dev')
```

Those will be lazily evaluated, and they will have a `config` object available.

**Comment by BeyondEvil** [comment]
Is the problem solved @OJFord ?

**Comment by OJFord** [comment]
Hi sorry I lost track of this, I'll close, but note that the readme still suggests the snippet in OP, which gives an error since pytest v5 and a deprecation warning in v4.

**Comment by nicoddemus** [comment]
Thanks @OJFord!

> but note that the readme still suggests the snippet in OP

Indeed, opened https://github.com/pytest-dev/pytest-base-url/pull/11 directly from GitHub UI. 😁
